services:
  backend:
    build:
      context: .
    container_name: fedegan-backend
    #command: python manage.py runserver 0.0.0.0:8000
    #command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: fedegan-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fedegan-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
