# Generated by Django 5.2.1 on 2025-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('bovino', 'Bovino'), ('porcino', 'Porcino')], max_length=10)),
                ('municipio', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('severidad', models.CharField(max_length=50)),
                ('descripción', models.TextField()),
            ],
        ),
    ]
